#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
//90 degree turn
//motor[motorD] = 40;
//motor[motorE] = 40;
//motor[motorF] = -40;
//motor[motorG] = -40;
//wait1Msec(812);

////180 degree turn
//motor[motorD] = 40;
//motor[motorE] = 40;
//motor[motorF] = -40;
//motor[motorG] = -40;
//wait1Msec(1624);

////360 degree turn
//motor[motorD] = 40;
//motor[motorE] = 40;
//motor[motorF] = -40;
//motor[motorG] = -40;
//wait1Msec(3248);

motor[motorD] = -100;
motor[motorE] = -100;
motor[motorF] = 30;
motor[motorG] = 30;
wait1Msec(10000000);

}
