#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     LEFT_MOTOR,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     RIGHT_MOTOR,   tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	motor[LEFT_MOTOR] = 100;
	wait1Msec(1000);
	motor[LEFT_MOTOR] = 0;
	motor[RIGHT_MOTOR] = 100;
	wait1Msec(1000);
	motor[RIGHT_MOTOR] = 0;


}
