#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
for(int count = 1; count<=4; count++)//start of a loop, will run 4 times
	{
motor[motorB] = 75;
motor[motorC] = 75;
wait1Msec(3400); // 1 second travel 7.5 inches at 50 power
//end of first length

motor[motorB] = 0;
motor[motorC] = 0;
wait1Msec(200);// wait for 1/10 of a second

motor[motorB] = 75;
motor[motorC] = 0;
wait1Msec(400);// swing turn
}
}
