#pragma config(Sensor, S1,     touchSensor,    sensorTouch)
#pragma config(Sensor, S3,     lightSensor,    sensorLightActive)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

while(true){ //Start of Loop//

if(SensorValue[lightSensor] < 50){
	motor[motorB] = 80;
	motor[motorC] = 0;
}

else {
	motor[motorB] = 0;
	motor[motorC] = 80;


}

wait1Msec(50);

}
}
